### ISSUE TITLE
什么时候支持导入导出钱包账户？

### ISSUE THREAD

**Issue by jojopoper** [StellarCN/firefly#1]
加个导入导出钱包账户功能，别让我自己创建钱包时候写那个巨长的S串，弄个二维码或者加密文件或者加密字符串什么的，这样在新手机上装了不仅可以同步账户信息，还能同步一些账户设置，比如密码，PIN码什么什么的东东。

**Comment by mazhaoyong** [comment]
支持导入导出钱包功能，默认采用二维码形式，暂时去掉了保存二维码到手机的功能，你可以做屏幕截图以备份。
PIN码（应用级）、密码（账户级）都支持。
同步账户信息部分就要牵扯到提供账户服务了，目前钱包的数据都是保存在本地的，暂时不会将个人账户数据上传到其他任何位置，所以不支持账户同步功能。
