### ISSUE TITLE
合并深度交易

### ISSUE THREAD

**Issue by Leavestonight** [StellarCN/firefly#112]
### Subject of the issue
当用户需要快速将手中的某资产兑换为另一种的时候，往往买1/卖1的数量不足够兑换。
此时需要合并可交易的市场深度。
此时用户可以选择按市场现在的深度对应的价格来进行下单的操作。
我们需要将这个深度对应的所有的挂单，以买卖价格差最大向价格差最小的顺序来完成交易；而不是直接以用户下单时的价格来完成交易。

### Your environment
- 2.1
- ios & android platform
- Firefly Wallet 2.1

**Comment by manran** [comment]
@imloama  https://github.com/StellarCN/firefly/commit/56854d40024c4a0d60cc254db1dfe591010b9cb3  已经解决这个了吗？

**Comment by imloama** [comment]
over
