### ISSUE TITLE
QRCode of contact/namecard can't be used in payment 

### ISSUE THREAD

**Issue by manran** [StellarCN/firefly#16]

**Comment by overcat** [comment]
The QR code is generated from this: `{"stellar":{"account":{"name":"黑色水星","id":"GAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}}}`
but the payment page only accepts `GAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

Is there any standard for generating QR code in Stellar?
