### ISSUE TITLE
Firefly APK Chinese by default, no obvious language selection

### ISSUE THREAD

**Issue by kfiresmith** [StellarCN/firefly#4]
I can't read Chinese, and wasn't able to find the right buttons to change the displayed language to English.  Please consider making language selection the first setup task upon installation.

Thanks!

**Comment by overcat** [comment]
I made a pull request #3  for the issue. The App can set the default language according to the device language. You may be able to see the feature in the next update.

**Comment by HongxuChen** [comment]
On "Deposit/Withdraw", for BTC (fchain.io) deposit/withdrawal, no need for displaying both Chinese and English.

**Comment by manran** [comment]
@kfiresmith @overcat  the new version (1.0.2)  have been published on google play.

**Comment by kfiresmith** [comment]
Thanks, I've installed it and English is working automatically.  Would you like feedback on Grammer and spelling from a native English speaker?

**Comment by HongxuChen** [comment]
@kfiresmith that would be fantastic! i've commented some on https://github.com/StellarCN/firefly/commit/49266bf1e312fcf17cd0f96bb2a161c3c30911ee however has never been good at English

**Comment by manran** [comment]
@kfiresmith Great!  FYI:   https://github.com/StellarCN/firefly/blob/master/src/locales/en.json

**Comment by kfiresmith** [comment]
Great, glad to participate.  I'll fork and work on it for a bit.
