### ISSUE TITLE
History display

### ISSUE THREAD

**Issue by HongxuChen** [StellarCN/firefly#5]
- [x] Sometimes it takes too long to retrieve the history of the transactions (providing a local cache?) ("My Wallet").
- [ ] Provide an "advanced mode" to display full history, and a normal mode to only display payment/trade relevant history.
- [x] When a contact already exists, the history should (1) display the alias/name of the contact (or in future the federation address) rather than the vanilla address; (2) not display the `Add Contact` button.
- [ ] Confusion of *using memo* for adding contacts, does firefly need it?

**Comment by mazhaoyong** [comment]
the memo of contact may be useful on sending asset

**Comment by HongxuChen** [comment]
@mazhaoyong for adding contacts, there is no need?

**Comment by mazhaoyong** [comment]
i think it's need
for adding contacts, the memo may be btc/etc address and so on.
when you send asset to some one from contacts, the memo from the contacts will fill to the transaction's memo.
