### ISSUE TITLE
iPhone上，部分用户使用不畅，基本操作都会卡顿。

### ISSUE THREAD

**Issue by Leavestonight** [StellarCN/firefly#71]
### Subject of the issue
iPhone上，部分用户使用不畅，基本操作都会卡顿。目前6/6S/7
都有反馈同样的问题，急需改善。

### Your environment
* 2.0 α version
* ios & android platform
* Firefly Wallet

**Comment by imloama** [comment]
caused by vuex storage plugin, fixed
