### ISSUE TITLE
App Crashed when Import Secret key

### ISSUE THREAD

**Issue by Leavestonight** [StellarCN/firefly#94]
### Subject of the issue
After 'Agree' the Terms Of Service,
Using 'Scan' the QR code to import the Secret key,
the App crashed.
‘同意’服务协议后，当使用‘扫描’二维码恢复密钥功能时，App闪退。

### Your environment
* 2.0.10
* ios , 9.1, 10.2 &11.3
* Firefly 2.0

**Comment by imloama** [comment]
bug from cordova-plugin-qrscan，user need to reinstall app, version of 2.1.x
