### ISSUE TITLE
The position of two assets sides turned upside down in [My offers]

### ISSUE THREAD

**Issue by Leavestonight** [StellarCN/firefly#96]
### Subject of the issue
Zh-CN:「我的记录」中，「我的委单」与「成交记录」中的委托记录与撤销记录交易中买卖方颠倒。
En: Every trade has base asset and counter asset , the position of two assets sides turned upside down in [My offers] and offer records & Cancelled offer records in [trading history].
![image](https://user-images.githubusercontent.com/38170964/40579194-bddc4788-6154-11e8-88e1-f166a70dc2f8.png)

### Your environment
*2.0.10
*iOS & android platform
*Firefly Wallet 2.0

**Comment by imloama** [comment]
fixed in 2.1.0
